from django.contrib import admin
from .models import LiveClass, LiveLesson

@admin.register(LiveClass)
class LiveClassAdmin(admin.ModelAdmin):
    list_display = (
        "title",
        "creator",
        "organization",
        "status",
        "start_date",
        "lesson_duration",
        "recurrence_type",
        "created_at",
    )
    readonly_fields = ("slug", "created_at", "updated_at")
    autocomplete_fields = ("organization", "creator", "course")
    list_filter = (
        "status",
        "recurrence_type",
        "organization",
        "created_at",
    )
    search_fields = (
        "title",
        "description",
        "creator__username",
        "organization__name",
    )
    ordering = ("-created_at",)
    date_hierarchy = "start_date"

    fieldsets = (
        (
            "General Information",
            {
                "fields": (
                    "title",
                    "slug",
                    "description",
                    "organization",
                    "creator",
                    "course",
                )
            },
        ),
        (
            "Scheduling & Recurrence",
            {
                "fields": (
                    "start_date",
                    "end_date",
                    "lesson_duration",
                    "recurrence_type",
                    "recurrence_days",
                    "recurrence_update_mode",
                ),
            },
        ),
        (
            "Access Control",
            {
                "fields": (
                    "requires_auth",
                    "allow_student_access",
                ),
            },
        ),
        (
            "Status & Metadata",
            {"fields": ("status", "created_at", "updated_at")},
        ),
    )

    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if not request.user.is_superuser:
            active_org = getattr(request, "active_organization", None)
            if active_org:
                return qs.filter(organization=active_org)
        return qs


@admin.register(LiveLesson)
class LiveLessonAdmin(admin.ModelAdmin):
    list_display = (
        "title",
        "live_class",
        "date",
        "start_time",
        "end_time",
        "has_video_config",  # Helper to see if Bunny ID is generated
    )
    # These should be read-only because they are generated by the system/API
    readonly_fields = (
        "bunny_video_id",
        "stream_key",
        "hls_playback_url",
        "chat_room_id",
        "created_at",
        "updated_at"
    )
    autocomplete_fields = ("live_class",)
    list_filter = ("live_class__organization", "date", "is_active")
    search_fields = ("title", "live_class__title", "live_class__creator__username", "bunny_video_id")
    ordering = ("date", "start_time")

    fieldsets = (
        (
            "Lesson Details",
            {
                "fields": (
                    "live_class",
                    "title",
                    "description",
                    "date",
                    "start_time",
                    "end_time",
                    "is_active",
                )
            },
        ),
        (
            "Video Configuration (Bunny.net)",
            {
                "classes": ("collapse",),
                "description": "These fields are auto-generated when the Tutor starts the class.",
                "fields": ("bunny_video_id", "stream_key", "hls_playback_url"),
            },
        ),
        (
            "Chat Configuration (Redis)",
            {
                "classes": ("collapse",),
                "fields": ("chat_room_id",),
            },
        ),
        (
            "Metadata",
            {"fields": ("created_at", "updated_at")},
        ),
    )

    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if not request.user.is_superuser:
            active_org = getattr(request, "active_organization", None)
            if active_org:
                return qs.filter(live_class__organization=active_org)
        return qs

    def has_video_config(self, obj):
        """Boolean icon to show if Bunny ID exists"""
        return bool(obj.bunny_video_id)
    has_video_config.boolean = True
    has_video_config.short_description = "Video Ready?"